# Generated by Django 5.2.3 on 2025-07-16 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='matches',
        ),
        migrations.AddField(
            model_name='item',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Is this item marked as claimed?'),
        ),
        migrations.AddField(
            model_name='item',
            name='private_note',
            field=models.TextField(blank=True, help_text='A secret detail about a FOUND item, for the owner to verify.', null=True),
        ),
        migrations.AlterField(
            model_name='claimattempt',
            name='claim_note',
            field=models.TextField(help_text='The secret detail provided by the claimant for verification.'),
        ),
        migrations.AlterField(
            model_name='claimattempt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_attempts', to='api.item'),
        ),
        migrations.AlterField(
            model_name='claimattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='lost', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.item'),
        ),
    ]
